<a href="https://colab.research.google.com/github/manesanika115/_ml2/blob/main/Ml5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
data = pd.read_csv("/content/car data.csv")
data

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
data.shape

(301, 9)

In [ ]:
data.isnull()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
296,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(2)

In [ ]:
data = data.drop_duplicates()
data

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
print("\n Duplicate values")
print(data.duplicated().sum())

 Duplicate values
0

In [ ]:
le = LabelEncoder()

In [ ]:
data.loc[:, "Fuel_Type"] = le.fit_transform(data["Fuel_Type"])
data.loc[:, "Seller_Type"] = le.fit_transform(data["Seller_Type"])
data.loc[:, "Transmission"] = le.fit_transform(data["Transmission"])

In [ ]:
print(data.head())

  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000         2
1      sx4  2013           4.75           9.54       43000         1
2     ciaz  2017           7.25           9.85        6900         2
3  wagon r  2011           2.85           4.15        5200         2
4    swift  2014           4.60           6.87       42450         1

  Seller_Type Transmission  Owner
0           0            1      0
1           0            1      0
2           0            1      0
3           0            1      0
4           0            1      0

In [ ]:
X = data[["Year","Present_Price","Kms_Driven","Fuel_Type","Seller_Type","Transmission","Owner"]]
Y = data["Selling_Price"]
print(X)

     Year  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0    2014           5.59       27000         2           0            1      0
1    2013           9.54       43000         1           0            1      0
2    2017           9.85        6900         2           0            1      0
3    2011           4.15        5200         2           0            1      0
4    2014           6.87       42450         1           0            1      0
..    ...            ...         ...       ...         ...          ...    ...
296  2016          11.60       33988         1           0            1      0
297  2015           5.90       60000         2           0            1      0
298  2009          11.00       87934         2           0            1      0
299  2017          12.50        9000         1           0            1      0
300  2016           5.90        5464         2           0            1      0

[299 rows x 7 columns]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
print("Predicted Selling Prices:")
print(Y_pred)

Predicted Selling Prices:
[ 7.54152814  7.60857724  1.36207444  6.83885956 11.26245861  4.54359165
  8.5845709   1.70919963  8.64713023 -0.9418582  10.14013852 -1.01376769
  0.67029971  1.5607731   5.06402181  5.09326915  1.318749    1.85805879
 21.49461753  0.88470811  0.94090952  2.51123502  5.61315878  0.21025908
  6.08428367  7.8732071   8.54440355  1.19083798  4.85632094  4.97326934
  6.43678966  5.58662973  6.09158985  2.71784907  2.94274014  6.78577292
  1.27045665 -4.49322868  1.41871851 10.46994115  7.19327321  8.88334013
  1.63138446  4.06239467  0.9789177  -2.1994379   8.20793597  4.37869605
  5.66258318 -0.58052448  0.6493802   0.18243912 10.51896108  9.30755118
  7.35828716  6.11959265  3.71478938  3.46322264  9.41844481  9.22737715]

In [ ]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [ ]:
print("Mean_Absolute Error:", mae)
print("Mean_Squared Error:", mse)
print("R2 Score:", r2)

Mean_Absolute Error: 1.5410718122837734
Mean_Squared Error: 6.67313744683074
R2 Score: 0.7410829335730333